export const readioFeatures = {
  auth: false,
  cloudSync: false,
  commerce: false,
  ai: false,
  opds: false,
  tts: false,
  annotations: false,
  notebook: false,
  proofreading: false,
  translation: false,
  parallelRead: false,
  speedReading: false,
  updater: false,
  telemetry: false,
  advancedSettings: false,
  localLibrary: true,
  localImport: true,
  reader: true,
  progress: true,
  basicReaderSettings: true,
} as const;
