import type { AIProviderCatalogEntry, AIProviderName, AISettings } from './types';

export const AI_PROVIDER_ORDER = [
  'openrouter',
  'openai',
  'gemini',
  'deepseek',
  'dashscope',
  'kimi',
  'mimo',
  'custom-openai-compatible',
] as const satisfies readonly AIProviderName[];

export const AI_PROVIDER_CATALOG: Record<AIProviderName, AIProviderCatalogEntry> = {
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    protocol: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyUrl: 'https://openrouter.ai/keys',
    apiKeyPlaceholder: 'sk-or-...',
    defaultModel: 'google/gemini-2.5-flash-lite',
    modelPresets: [
      { id: 'google/gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite' },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o mini' },
      { id: 'deepseek/deepseek-chat', label: 'DeepSeek Chat' },
      { id: 'qwen/qwen-2.5-72b-instruct', label: 'Qwen 2.5 72B Instruct' },
    ],
  },
  openai: {
    id: 'openai',
    label: 'OpenAI',
    protocol: 'openai-compatible',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
    apiKeyPlaceholder: 'sk-...',
    defaultModel: 'gpt-4o-mini',
    modelPresets: [
      { id: 'gpt-4o-mini', label: 'GPT-4o mini' },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini' },
      { id: 'gpt-4.1-nano', label: 'GPT-4.1 nano' },
    ],
  },
  gemini: {
    id: 'gemini',
    label: 'Google Gemini',
    protocol: 'openai-compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    apiKeyUrl: 'https://aistudio.google.com/app/apikey',
    apiKeyPlaceholder: 'AIza...',
    defaultModel: 'gemini-2.0-flash-lite',
    modelPresets: [
      { id: 'gemini-2.0-flash-lite', label: 'Gemini 2.0 Flash Lite' },
      { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
      { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash' },
    ],
  },
  deepseek: {
    id: 'deepseek',
    label: 'DeepSeek',
    protocol: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    apiKeyPlaceholder: 'sk-...',
    defaultModel: 'deepseek-v4-flash',
    modelPresets: [
      { id: 'deepseek-v4-flash', label: 'DeepSeek V4 Flash' },
      { id: 'deepseek-v4-pro', label: 'DeepSeek V4 Pro' },
    ],
    chatRequestOptions: {
      thinking: { type: 'enabled' },
      reasoning_effort: 'high',
    },
  },
  dashscope: {
    id: 'dashscope',
    label: 'DashScope / Qwen',
    protocol: 'openai-compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKeyUrl: 'https://dashscope.console.aliyun.com/apiKey',
    apiKeyPlaceholder: 'sk-...',
    defaultModel: 'qwen-plus',
    modelPresets: [
      { id: 'qwen-plus', label: 'Qwen Plus' },
      { id: 'qwen-turbo', label: 'Qwen Turbo' },
      { id: 'qwen-max', label: 'Qwen Max' },
    ],
  },
  kimi: {
    id: 'kimi',
    label: 'Kimi / Moonshot',
    protocol: 'openai-compatible',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
    apiKeyPlaceholder: 'sk-...',
    defaultModel: 'moonshot-v1-8k',
    modelPresets: [
      { id: 'moonshot-v1-8k', label: 'Moonshot v1 8K' },
      { id: 'moonshot-v1-32k', label: 'Moonshot v1 32K' },
      { id: 'moonshot-v1-128k', label: 'Moonshot v1 128K' },
    ],
  },
  mimo: {
    id: 'mimo',
    label: 'Xiaomi MiMo',
    protocol: 'openai-compatible',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
    apiKeyUrl: 'https://platform.mimodax.com',
    apiKeyPlaceholder: 'tp-...',
    defaultModel: 'mimo-v2.5-pro',
    modelPresets: [
      { id: 'mimo-v2.5-pro', label: 'MiMo V2.5 Pro' },
      { id: 'mimo-v2.5', label: 'MiMo V2.5' },
      { id: 'mimo-v2-pro', label: 'MiMo V2 Pro' },
      { id: 'mimo-v2-omni', label: 'MiMo V2 Omni' },
    ],
  },
  'custom-openai-compatible': {
    id: 'custom-openai-compatible',
    label: 'Custom OpenAI-compatible',
    protocol: 'openai-compatible',
    baseUrl: 'https://api.example.com/v1',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
    apiKeyPlaceholder: 'sk-...',
    defaultModel: 'custom-model',
    modelPresets: [{ id: 'custom-model', label: 'Custom Model ID' }],
  },
};

export const DEFAULT_AI_SETTINGS: AISettings = {
  enabled: false,
  showReaderAIEntrypoints: true,
  provider: 'openrouter',
  providerApiKeys: {},
  providerModels: { openrouter: AI_PROVIDER_CATALOG.openrouter.defaultModel },
  providerEmbeddingModels: {},
  spoilerProtection: true,
  maxContextChunks: 10,
  indexingMode: 'on-demand',
};
